[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "LEO-S9"
authors = [{name = "Fabricio", email = "fabricioprol@hotmail.com"}]
dynamic = ["version", "description"]
